language: python

python:
  - 3.6

install:
  - pip install -U pytest pytest-cov coveralls
  - pip install -r requirements.txt

script:
  - python -m pytest --cov=pymlogit

after_sucess:
  - coveralls